### PR TITLE
Pin mcp<2 so Chapter 4's FastMCP import works

### PR DESCRIPTION
**Pull request by durrello**
## What
Add an explicit `mcp>=1.0,<2` dependency in `pyproject.toml`.

## Why
Chapter 4 (`4_mcp_integration/dice_roll_mcp_server.py`) uses `from mcp.server import FastMCP`. That
import path only exists in mcp 1.x. In mcp 2.x the class was renamed to `MCPServer`, so a fresh,
unpinned install pulls mcp 2.x and Chapter 4 fails with an `ImportError` (and the client then raises
`MCPClientInitializationError`).

## Repro
On a clean environment, `uv sync` (or `pip install .`) currently resolves `mcp==2.x`, then
`python 4_mcp_integration/dice_roll_mcp_server.py` raises:
`ImportError: cannot import name 'FastMCP' from 'mcp.server'`.

## Fix
Pin `mcp>=1.0,<2`. Verified Chapter 4 server + client work on `mcp 1.30.0`.

## Notes
The README says the workshop intentionally does not pin versions; this is the minimal pin needed to
keep Chapter 4 working until the code is migrated to the mcp 2.x `MCPServer` API. Happy to instead
submit a 2.x migration if you prefer that direction.

### CODE REVIEW

**Comment by TheWitcherish** [comment]
Thank you very much for your PR. Fix has been implemented. Closing this PR.
